/* FEP Compass — stress-test scenario battery for the AI Compliance Analyst.
   Each scenario mirrors the Analyst's WHO/WHAT/WHERE/WHY/AMOUNT/CONTEXT intake
   (see app.js's `af-run` handler) and is checked against ground truth taken
   directly from the real FEP Notice text in kb.js — not from the model's own
   output, so a confidently wrong (or hallucinated-citation) answer fails.

   expectVerdict      — acceptable VALID_VERDICTS values (array; >1 means the
                         provisions leave room for either reading).
   expectRefHints      — substrings that must appear in the citation, matched
                         after normalising "Para X" / "FAQ QX" tokens (see
                         extractRefTokens in run-stress-test.js). Confirms the
                         model grounded its answer in the *intended* provision,
                         not just *a* real one for that Notice.
   mustNotMention       — substrings that must NOT appear in explanation/
                         citation — for asserting a rule is correctly judged
                         inapplicable (e.g. no RM1M cap when there's no DRB). */
'use strict';

module.exports = [
  // ── Notice 1 — Dealings in Currency, Gold and Other Precious Metals ──
  {
    id: 'n1-01', notice: 1,
    title: 'Spot FX with a LOB to settle an import payment',
    who: 'Resident company (importer)',
    what: 'Buying USD against Ringgit on a spot basis with a Licensed Onshore Bank to settle an import payment',
    amount: 500000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    rationale: 'Part A, Para 1: a Resident may buy/sell FCY vs Ringgit on spot basis with a LOB for its own account.',
  },
  {
    id: 'n1-02', notice: 1,
    title: 'Forward FX contract with an unlicensed money changer',
    who: 'Resident trading company',
    what: 'Entering a 3-month forward contract to sell EUR against Ringgit with a local currency dealer that is NOT a Licensed Onshore Bank, to hedge an anticipated export receivable',
    expectVerdict: ['NOT_PERMITTED'],
    rationale: 'Forward Basis transactions must be undertaken with a LOB (Part A, Para 1) — an unlicensed counterparty is not permitted for forwards.',
  },
  {
    id: 'n1-03', notice: 1,
    title: 'Unregistered institutional investor using Dynamic Hedging',
    who: 'Resident Institutional Investor (asset manager), NOT registered under the Dynamic Hedging Framework',
    what: 'Enter plain vanilla forward contracts to sell FCY against Ringgit, hedging up to 100% of its FCY-denominated securities, without documentary evidence',
    expectVerdict: ['REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 requires one-off FEP Authority registration under the Dynamic Hedging Framework before this is allowed.',
  },
  {
    id: 'n1-04', notice: 1,
    title: 'FCY-vs-FCY spot deal with a LOB',
    who: 'Resident individual',
    what: 'Buying USD against EUR on a spot basis with a Licensed Onshore Bank',
    amount: 20000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part A, Para 5: a Resident may buy/sell FCY against another FCY with a LOB.',
  },

  // ── Notice 2 — Borrowing, Lending and Guarantee ──
  {
    id: 'n2-01', notice: 2,
    title: 'Individual Ringgit borrowing from a Non-Resident friend, within RM1M cap',
    who: 'Resident individual',
    what: 'Borrowing RM800,000 in Ringgit from a Non-Resident friend (not an immediate family member or employer)',
    amount: 800000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    mustNotMention: ['RM10 million', 'RM100 million'],
    rationale: 'Part A, Para 2 allows a Resident Individual to borrow up to RM1 million in aggregate in Ringgit from a Non-Resident (excl. NRFI) — RM800,000 is within that cap.',
  },
  {
    id: 'n2-02', notice: 2,
    title: 'Individual Ringgit borrowing from a Non-Resident friend, exceeding RM1M cap',
    who: 'Resident individual',
    what: 'Borrowing RM1.5 million in Ringgit from a Non-Resident friend (not an immediate family member or employer)',
    amount: 1500000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 caps such Ringgit borrowing at RM1 million aggregate — RM1.5 million exceeds it.',
  },
  {
    id: 'n2-03', notice: 2,
    title: 'Entity FCY borrowing from its Direct Shareholder',
    who: 'Resident company',
    what: 'Borrowing USD80 million equivalent in Foreign Currency from its Non-Resident Direct Shareholder (parent company)',
    amount: 80000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para9'],
    mustNotMention: ['RM100 million'],
    rationale: 'Part B, Para 9(b): FCY borrowing from a Direct Shareholder is unlimited — the RM100 million cap (Para 10) only applies to borrowing from outside the Group/NRFI/out-of-group SPV.',
  },
  {
    id: 'n2-04', notice: 2,
    title: 'Entity FCY borrowing from an unrelated Non-Resident, exceeding RM100M cap',
    who: 'Resident company',
    what: 'Borrowing USD120 million equivalent in Foreign Currency from a Non-Resident company outside its Group (not a LOB, not a Direct Shareholder, not a Group entity)',
    amount: 120000000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para10'],
    rationale: 'Part B, Para 10 caps FCY borrowing from outside the Group at RM100 million equivalent on a group basis — USD120 million well exceeds it.',
  },
  {
    id: 'n2-05', notice: 2,
    title: 'Individual Ringgit borrowing from an immediate family member',
    who: 'Resident individual',
    what: 'Borrowing RM2 million in Ringgit from his Non-Resident spouse',
    amount: 2000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 1: Ringgit borrowing from a Non-Resident Immediate Family Member is unlimited — the RM1 million cap (Para 2) does not apply here.',
  },

  // ── Notice 3 — Investment in Foreign Currency Asset (DRB) ──
  {
    id: 'n3-01', notice: 3,
    title: 'Regression: one housing loan + one vehicle loan together is still WITHOUT DRB',
    who: 'Resident individual with exactly ONE outstanding housing loan AND exactly ONE outstanding vehicle loan at the same time, and no other Ringgit borrowing from any Resident',
    what: 'Converting RM1.5 million from Ringgit to invest in foreign-listed stocks',
    amount: 1500000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million', 'RM2 million'],
    rationale: 'One housing loan + one vehicle loan is the excluded DRB combination, NOT "more than one" of either type — this Resident is WITHOUT DRB, so Part A Para 1 (UNLIMITED) governs, not the RM1M Para 2 cap.',
  },
  {
    id: 'n3-02', notice: 3,
    title: 'Two housing loans triggers DRB, RM1M cap exceeded',
    who: 'Resident individual with TWO outstanding housing loans and no other Ringgit borrowing',
    what: 'Converting RM1.2 million from Ringgit to invest in a foreign currency fixed deposit',
    amount: 1200000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'TWO housing loans (more than one of the same type) gives this Resident DRB, so the RM1 million/year conversion cap (Part A, Para 2(c)) applies and is exceeded.',
  },
  {
    id: 'n3-03', notice: 3,
    title: 'No Ringgit borrowing at all — unlimited investment',
    who: 'Resident individual with no Ringgit borrowing of any kind',
    what: 'Converting RM5 million from Ringgit to invest in foreign-listed stocks',
    amount: 5000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 1: a Resident Individual without DRB may invest any amount in FCY assets.',
  },
  {
    id: 'n3-04', notice: 3,
    title: 'Joint investment, neither party has DRB — must stay unlimited',
    who: 'Two Resident individuals, joint accountholders, NEITHER of whom has any Domestic Ringgit Borrowing',
    what: 'Jointly converting RM3 million from their joint Ringgit account into a joint foreign currency fixed deposit',
    amount: 3000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million', 'RM2 million'],
    rationale: 'With no DRB on either side, Part A Para 1 (UNLIMITED) governs the whole joint investment — the RM1M/RM2M joint-FCA FAQ only engages when at least one party has DRB.',
  },
  {
    id: 'n3-05', notice: 3,
    title: 'Joint investment, one party has DRB — RM2M combined cap exceeded',
    who: 'Two Resident individuals, joint accountholders; one has DRB (two outstanding vehicle loans), the other has none',
    what: 'Jointly converting RM2.5 million from their joint Ringgit account into a joint foreign currency fixed deposit',
    amount: 2500000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['q7'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q7: DRB in any one joint party caps the WHOLE joint investment at RM1M per person / RM2M combined for two parties — RM2.5 million exceeds it.',
  },
  {
    id: 'n3-06', notice: 3,
    title: 'Entity with DRB using LOB FCY borrowing for Direct Investment Abroad',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Using RM80 million equivalent of Foreign Currency borrowing obtained from a Licensed Onshore Bank to fund a Direct Investment Abroad (acquiring 25% equity in a foreign company)',
    amount: 80000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    mustNotMention: ['RM50 million'],
    rationale: 'Part B, Para 4(b): LOB FCY borrowing used for DIA is unlimited — the RM50 million/year cap (Para 4(c)) only applies to conversion-funded, non-DIA investment.',
  },

  // ── Notice 4 — Payment and Receipt ──
  {
    id: 'n4-01', notice: 4,
    title: 'FCY payment from Resident to Non-Resident for an import',
    who: 'Resident company',
    what: 'Paying USD300,000 to a Non-Resident supplier in Foreign Currency to settle an import of goods',
    amount: 300000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5: a Resident may pay a Non-Resident in FCY for any purpose except a short list of derivative transactions — an import settlement is not on that list.',
  },
  {
    id: 'n4-02', notice: 4,
    title: 'FCY payment between two Residents for an unlisted domestic purpose',
    who: 'Resident individual',
    what: 'Paying another Resident individual in US Dollars for rental of a holiday home in Malaysia (both parties are Malaysian residents, no family relationship, no LOB or Global Supply Chain involvement)',
    amount: 10000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part C, Para 4 only permits FCY payment between Residents for a specific listed set of purposes (family, education/employment/migration abroad, LOB dealings, Global Supply Chain, etc.) — domestic holiday-home rent is not on that list.',
  },
  {
    id: 'n4-03', notice: 4,
    title: 'Non-Resident repatriating Ringgit-asset divestment proceeds',
    who: 'Non-Resident individual',
    what: 'Repatriating proceeds from the sale of a Ringgit-denominated asset out of Malaysia, converting the proceeds into Foreign Currency before transfer',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para8'],
    rationale: 'Part E, Para 8: a Non-Resident may repatriate funds from Malaysia provided repatriation is in FCY and the Ringgit-to-FCY conversion follows Notice 1 Part B.',
  },
  {
    id: 'n4-04', notice: 4,
    title: 'Ringgit payment to a Non-Resident from a court judgement',
    who: 'Resident company',
    what: 'Making a Ringgit payment to a Non-Resident in Malaysia arising from a court judgement, where the underlying transaction complies with the FEP Notices',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para3'],
    rationale: 'Part B, Para 3 permits Ringgit payment/receipt for a court judgement where the underlying transaction is FEP-compliant.',
  },

  // ── Notice 5 — Securities and Financial Instruments ──
  {
    id: 'n5-01', notice: 5,
    title: 'Resident issuing a Ringgit bond to a Non-Resident',
    who: 'Resident company',
    what: 'Issuing a Ringgit-denominated corporate bond in Malaysia to a Non-Resident institutional investor',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para1'],
    rationale: 'Part A, Para 1(a): permitted, but as a debt security issuance it must also comply with Notice 2 borrowing limits.',
  },
  {
    id: 'n5-02', notice: 5,
    title: 'Non-Resident issuing an FCY bond in Malaysia',
    who: 'Non-Resident company',
    what: 'Issuing a Foreign Currency-denominated bond in Malaysia to any investor',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2-3: a Non-Resident may issue an FCY-denominated security in Malaysia to any person.',
  },
  {
    id: 'n5-03', notice: 5,
    title: 'Bursa Malaysia offering an exchange-rate-linked Ringgit instrument',
    who: 'Bursa Malaysia',
    what: 'Offering a Non-Resident a Ringgit-denominated structured note whose payout is linked to the USD/MYR exchange rate',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para8'],
    rationale: 'Part B, Para 8 explicitly excludes exchange-rate-referenced financial instruments from what Bursa Malaysia may offer Non-Residents.',
  },
  {
    id: 'n5-04', notice: 5,
    title: 'Resident subscribing to a Notice-5 security',
    who: 'Resident individual',
    what: 'Subscribing to a Ringgit-denominated corporate bond issued under Notice 5, subject to compliance with Notices 2, 3 and 4',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para9'],
    rationale: 'Part C, Para 9-10: subscription is permitted subject to compliance with Notices 2, 3 and 4.',
  },

  // ── Notice 6 — Import and Export of Currency ──
  {
    id: 'n6-01', notice: 6,
    title: 'Strict cap: traveller exporting RM5,000 cash',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Carrying RM5,000 in Ringgit currency notes out of Malaysia on departure',
    amount: 5000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['ringgit (export)'],
    rationale: 'A traveller may take out at most RM1,000 in Ringgit notes per trip — amounts above that are NOT permitted under any circumstances (no approval pathway exists for this one).',
  },
  {
    id: 'n6-02', notice: 6,
    title: 'Within cap: traveller exporting RM800 cash',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Carrying RM800 in Ringgit currency notes out of Malaysia on departure',
    amount: 800, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['ringgit (export)'],
    rationale: 'RM800 is within the RM1,000 per-trip cap on exporting Ringgit notes.',
  },
  {
    id: 'n6-03', notice: 6,
    title: 'Undeclared Ringgit import above threshold',
    who: 'Traveller entering Malaysia',
    what: 'Bringing RM15,000 in Ringgit currency notes into Malaysia without declaring it to Customs on arrival',
    amount: 15000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['ringgit (import)'],
    rationale: 'Import of Ringgit above RM10,000 must be declared to Customs — bringing it in undeclared is not permitted.',
  },
  {
    id: 'n6-04', notice: 6,
    title: 'Undeclared FCY export above threshold',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Taking USD10,000 in foreign currency notes out of Malaysia without declaring it to the Royal Malaysian Customs Department',
    amount: 10000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['foreign currency'],
    rationale: 'Amounts exceeding RM30,000 equivalent in FCY must be declared to Customs; USD10,000 (well above that, at typical exchange rates) taken out undeclared is a violation.',
  },

  // ── Notice 7 — Export of Goods ──
  {
    id: 'n7-01', notice: 7,
    title: 'Compliant export proceeds receipt',
    who: 'Resident exporter',
    what: 'Receiving the full value of export proceeds within 4 months of shipment, credited into a Trade FCA maintained with a Licensed Onshore Bank',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(a)', 'para1(c)'],
    rationale: 'Part A, Para 1(a)/(c): full-value receipt within 6 months into a Ringgit account or Trade FCA with a LOB is the standard compliant pattern.',
  },
  {
    id: 'n7-02', notice: 7,
    title: 'Export proceeds overdue beyond 6 months, no approved exception',
    who: 'Resident exporter',
    what: 'Export proceeds still not received 8 months after shipment date, and none of the approved Appendix C circumstances (buyer difficulties, disputes, consignment, testing) apply',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c): proceeds must be received within 6 months, extendable to 24 months ONLY in approved Appendix C circumstances — none apply here.',
  },
  {
    id: 'n7-03', notice: 7,
    title: 'Large exporter has not filed the required report',
    who: 'Resident exporter with annual gross exports of RM300 million in the preceding year',
    what: 'Has not submitted any report to the FEP Authority despite exceeding the RM250 million reporting threshold',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para4'],
    rationale: 'Part C, Para 4: exporters with annual gross exports above RM250 million must report to the FEP Authority as and when required — not having reported is non-compliant.',
  },
  {
    id: 'n7-04', notice: 7,
    title: 'Outstanding proceeds beyond 24 months, not notified',
    who: 'Resident exporter',
    what: 'Export proceeds still outstanding 25 months after shipment, and the exporter has not notified the FEP Authority of the outstanding amount',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5: proceeds outstanding beyond 24 months must be notified to the FEP Authority within 21 days after year-end — failing to notify is non-compliant.',
  },
];
