/* FEP Compass — stress-test scenario battery for the AI Compliance Analyst.
   Each scenario mirrors the Analyst's WHO/WHAT/WHERE/WHY/AMOUNT/CONTEXT intake
   (see app.js's `af-run` handler) and is checked against ground truth taken
   directly from the real FEP Notice text in kb.js — not from the model's own
   output, so a confidently wrong (or hallucinated-citation) answer fails.

   expectVerdict      — acceptable VALID_VERDICTS values (array; >1 means the
                         provisions leave room for either reading).
   expectRefHints      — substrings that must appear in the citation, matched
                         after normalising "Para X" / "FAQ QX" tokens (see
                         extractRefTokens in run-stress-test.js). Confirms the
                         model grounded its answer in the *intended* provision,
                         not just *a* real one for that Notice.
   mustNotMention       — substrings that must NOT appear in explanation/
                         citation — for asserting a rule is correctly judged
                         inapplicable (e.g. no RM1M cap when there's no DRB).

   150 scenarios total — N1/N5/N6: 10 each (lower transaction volume); N2/N7:
   30 each; N3/N4: 27/33 (a citation-grounding fix moved 3 scenarios from N3
   to N4, since their cited authority was actually Notice 4's FAQ Q7). */
'use strict';

module.exports = [
  // ── Notice 1 — Dealings in Currency, Gold and Other Precious Metals ──
  {
    id: 'n1-01', notice: 1,
    title: 'Spot FX with a LOB to settle an import payment',
    who: 'Resident company (importer)',
    what: 'Buying USD against Ringgit on a spot basis with a Licensed Onshore Bank to settle an import payment',
    amount: 500000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    rationale: 'Part A, Para 1: a Resident may buy/sell FCY vs Ringgit on spot basis with a LOB for its own account.',
  },
  {
    id: 'n1-02', notice: 1,
    title: 'Forward FX contract with an unlicensed money changer',
    who: 'Resident trading company',
    what: 'Entering a 3-month forward contract to sell EUR against Ringgit with a local currency dealer that is NOT a Licensed Onshore Bank, to hedge an anticipated export receivable',
    expectVerdict: ['NOT_PERMITTED'],
    rationale: 'Forward Basis transactions must be undertaken with a LOB (Part A, Para 1) — an unlicensed counterparty is not permitted for forwards.',
  },
  {
    id: 'n1-03', notice: 1,
    title: 'Unregistered institutional investor using Dynamic Hedging',
    who: 'Resident Institutional Investor (asset manager), NOT registered under the Dynamic Hedging Framework',
    what: 'Enter plain vanilla forward contracts to sell FCY against Ringgit, hedging up to 100% of its FCY-denominated securities, without documentary evidence',
    expectVerdict: ['REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 requires one-off FEP Authority registration under the Dynamic Hedging Framework before this is allowed.',
  },
  {
    id: 'n1-04', notice: 1,
    title: 'FCY-vs-FCY spot deal with a LOB',
    who: 'Resident individual',
    what: 'Buying USD against EUR on a spot basis with a Licensed Onshore Bank',
    amount: 20000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part A, Para 5: a Resident may buy/sell FCY against another FCY with a LOB.',
  },
  {
    id: 'n1-05', notice: 1,
    title: 'Resident unwinding a Forward Basis contract whose Firm Commitment was a Portfolio Investment',
    who: 'Resident asset management company',
    what: 'Attempting to unwind a Forward Basis transaction with a Licensed Onshore Bank where the underlying Firm Commitment is a Portfolio Investment (tradable equity holding below 10%)',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para1'],
    rationale: 'Part A, Para 1(2): a Resident may unwind a Forward Basis transaction with any LOB EXCEPT where the Firm Commitment is a Portfolio Investment — that specific unwind is excluded.',
  },
  {
    id: 'n1-06', notice: 1,
    title: 'Registered Resident Institutional Investor unwinding a Dynamic Hedging forward',
    who: 'Resident Institutional Investor, registered under the Dynamic Hedging Framework',
    what: 'Unwinding a plain vanilla forward contract entered under the Dynamic Hedging Framework, with a Licensed Onshore Bank',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2(2): a registered Resident Institutional Investor may unwind its Para 2(1) Dynamic Hedging forward contract with any LOB.',
  },
  {
    id: 'n1-07', notice: 1,
    title: 'Spot FX deal with a Licensed Money Changer, within MSBA scope',
    who: 'Resident individual traveller',
    what: 'Buying USD against Ringgit on a spot basis with a Licensed Money Changer in accordance with the MSBA',
    amount: 3000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para14'],
    rationale: 'Part C, Para 14: a Resident or Non-Resident may buy/sell FCY against Ringgit on Spot Basis with a Licensed Money Changer per the MSBA.',
  },
  {
    id: 'n1-08', notice: 1,
    title: 'Resident Entity transacting FX on behalf of a Group entity that is a Financial Institution',
    who: 'Resident Entity (treasury centre) acting for a Group entity that is itself a licensed bank',
    what: 'Buying Foreign Currency against Ringgit with a LOB on behalf of a Group entity that is a Financial Institution',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para3'],
    rationale: 'Part A, Para 3 only permits a Resident Entity to transact FX on behalf of a Group Principal that is NOT a Financial Institution or NRFI — here the Principal is a Financial Institution, so the exemption does not apply.',
  },
  {
    id: 'n1-09', notice: 1,
    title: 'Non-Resident Institutional Investor exceeding the Dynamic Hedging buy-side threshold',
    who: 'Non-Resident Institutional Investor, registered under the Dynamic Hedging Framework',
    what: 'Buying FCY against Ringgit forward contracts amounting to 40% of its Ringgit-denominated asset exposure (which only permits up to 25% on the buy side)',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para7'],
    rationale: 'Part B, Para 7: a registered Non-Resident Institutional Investor may buy FCY against Ringgit up to only 25% of its Ringgit-asset exposure (selling is capped at 100%) — 40% exceeds the buy-side limit.',
  },
  {
    id: 'n1-10', notice: 1,
    title: 'Importing gold bars into Malaysia',
    who: 'Resident bullion trading company',
    what: 'Importing gold bars into Malaysia for resale',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para16'],
    rationale: 'Part D, Para 16(b): a person is allowed to import gold or other precious metals.',
  },

  // ── Notice 2 — Borrowing, Lending and Guarantee ──
  {
    id: 'n2-01', notice: 2,
    title: 'Individual Ringgit borrowing from a Non-Resident friend, within RM1M cap',
    who: 'Resident individual',
    what: 'Borrowing RM800,000 in Ringgit from a Non-Resident friend (not an immediate family member or employer)',
    amount: 800000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    mustNotMention: ['RM10 million', 'RM100 million'],
    rationale: 'Part A, Para 2 allows a Resident Individual to borrow up to RM1 million in aggregate in Ringgit from a Non-Resident (excl. NRFI) — RM800,000 is within that cap.',
  },
  {
    id: 'n2-02', notice: 2,
    title: 'Individual Ringgit borrowing from a Non-Resident friend, exceeding RM1M cap',
    who: 'Resident individual',
    what: 'Borrowing RM1.5 million in Ringgit from a Non-Resident friend (not an immediate family member or employer)',
    amount: 1500000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 caps such Ringgit borrowing at RM1 million aggregate — RM1.5 million exceeds it.',
  },
  {
    id: 'n2-03', notice: 2,
    title: 'Entity FCY borrowing from its Direct Shareholder',
    who: 'Resident company',
    what: 'Borrowing USD80 million equivalent in Foreign Currency from its Non-Resident Direct Shareholder (parent company)',
    amount: 80000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para9'],
    mustNotMention: ['RM100 million'],
    rationale: 'Part B, Para 9(b): FCY borrowing from a Direct Shareholder is unlimited — the RM100 million cap (Para 10) only applies to borrowing from outside the Group/NRFI/out-of-group SPV.',
  },
  {
    id: 'n2-04', notice: 2,
    title: 'Entity FCY borrowing from an unrelated Non-Resident, exceeding RM100M cap',
    who: 'Resident company',
    what: 'Borrowing USD120 million equivalent in Foreign Currency from a Non-Resident company outside its Group (not a LOB, not a Direct Shareholder, not a Group entity)',
    amount: 120000000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para10'],
    rationale: 'Part B, Para 10 caps FCY borrowing from outside the Group at RM100 million equivalent on a group basis — USD120 million well exceeds it.',
  },
  {
    id: 'n2-05', notice: 2,
    title: 'Individual Ringgit borrowing from an immediate family member',
    who: 'Resident individual',
    what: 'Borrowing RM2 million in Ringgit from his Non-Resident spouse',
    amount: 2000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 1: Ringgit borrowing from a Non-Resident Immediate Family Member is unlimited — the RM1 million cap (Para 2) does not apply here.',
  },
  {
    id: 'n2-06', notice: 2,
    title: 'Individual Ringgit borrowing from employer in Malaysia',
    who: 'Resident individual employee',
    what: 'Borrowing RM3 million in Ringgit from his employer in Malaysia for use in Malaysia, per the employment contract terms',
    amount: 3000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 1(b): Ringgit borrowing from an employer in Malaysia for use in Malaysia is unlimited, subject to employment contract terms.',
  },
  {
    id: 'n2-07', notice: 2,
    title: 'Boundary: individual Ringgit borrowing exactly at the RM1M cap',
    who: 'Resident individual',
    what: 'Borrowing exactly RM1,000,000 in aggregate in Ringgit from a Non-Resident friend (not immediate family, not employer, not NRFI)',
    amount: 1000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 allows up to RM1 million in aggregate — exactly RM1,000,000 is within (not exceeding) that cap.',
  },
  {
    id: 'n2-08', notice: 2,
    title: 'Individual FCY borrowing from immediate family member, unlimited',
    who: 'Resident individual',
    what: 'Borrowing USD5 million equivalent in Foreign Currency from his Immediate Family Member (brother)',
    amount: 5000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para3'],
    mustNotMention: ['RM10 million'],
    rationale: 'Part A, Para 3: FCY borrowing from an Immediate Family Member is unlimited — the RM10 million cap (Para 4) does not apply.',
  },
  {
    id: 'n2-09', notice: 2,
    title: 'Individual FCY borrowing from a LOB, within RM10M cap',
    who: 'Resident individual',
    what: 'Borrowing RM8 million equivalent in Foreign Currency from a Licensed Onshore Bank',
    amount: 8000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part A, Para 4: a Resident Individual may borrow up to RM10 million equivalent in aggregate in FCY from a LOB or Non-Resident — RM8 million is within that cap.',
  },
  {
    id: 'n2-10', notice: 2,
    title: 'Individual FCY borrowing from a Non-Resident, exceeding RM10M cap',
    who: 'Resident individual',
    what: 'Borrowing USD15 million equivalent in Foreign Currency from a Non-Resident business partner (not family, not a LOB)',
    amount: 15000000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para4'],
    rationale: 'Part A, Para 4 caps FCY borrowing by a Resident Individual at RM10 million equivalent in aggregate — USD15 million equivalent exceeds it.',
  },
  {
    id: 'n2-11', notice: 2,
    title: 'Individual refinancing existing approved Ringgit borrowing',
    who: 'Resident individual',
    what: 'Refinancing the outstanding principal and accrued interest of a previously-approved RM1 million Ringgit borrowing from a Non-Resident friend, on the same terms',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part A, Para 5: a Resident Individual may refinance outstanding approved Borrowing under paragraphs 1 to 4, subject to compliance with the respective paragraph.',
  },
  {
    id: 'n2-12', notice: 2,
    title: 'Entity Ringgit borrowing from a Non-Resident Direct Shareholder for Real Sector Activity',
    who: 'Resident company',
    what: 'Borrowing RM50 million in Ringgit from its Non-Resident Direct Shareholder to finance a manufacturing plant expansion (Real Sector Activity) in Malaysia',
    amount: 50000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para6'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part B, Para 6: Ringgit borrowing from a Non-Resident within the Group (including a Direct Shareholder) to finance Real Sector Activity in Malaysia is unlimited.',
  },
  {
    id: 'n2-13', notice: 2,
    title: 'Entity Ringgit borrowing via non-tradable Corporate Bond issued to an out-of-Group Non-Resident',
    who: 'Resident company',
    what: 'Issuing a non-tradable Ringgit-denominated Corporate Bond to a Non-Resident Entity outside its Group (not a NRFI exemption)',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para7'],
    rationale: 'Part B, Para 7 excludes a non-tradable Ringgit Corporate Bond or Sukuk issued to a Non-Resident Entity outside the Resident Entity\'s Group (or a NRFI) from the general permission.',
  },
  {
    id: 'n2-14', notice: 2,
    title: 'Entity Ringgit borrowing from an external Non-Resident, within RM1M cap',
    who: 'Resident company',
    what: 'Borrowing RM900,000 in Ringgit for use in Malaysia from a Non-Resident company outside its Group, excluding a NRFI',
    amount: 900000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para8'],
    rationale: 'Part B, Para 8(a): a Resident Entity may borrow up to RM1 million in aggregate in Ringgit for use in Malaysia from a Non-Resident excluding a NRFI — RM900,000 is within that cap.',
  },
  {
    id: 'n2-15', notice: 2,
    title: 'Entity Ringgit borrowing from a Multilateral Development Bank, unlimited',
    who: 'Resident company',
    what: 'Borrowing RM200 million in Ringgit for use in Malaysia from a Multilateral Development Bank',
    amount: 200000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para8'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part B, Para 8(b): Ringgit borrowing in any amount from a Multilateral Development Bank or Qualified Development Financial Institution is unlimited.',
  },
  {
    id: 'n2-16', notice: 2,
    title: 'Entity FCY borrowing from an Entity within its Group, unlimited',
    who: 'Resident company',
    what: 'Borrowing USD60 million equivalent in Foreign Currency from a sister company within its Group (not a NRFI, not a SPV)',
    amount: 60000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para9'],
    mustNotMention: ['RM100 million'],
    rationale: 'Part B, Para 9(b): FCY borrowing in any amount from an Entity within the Resident Entity\'s Group is unlimited (excluding a NRFI or out-of-Group SPV, which fall under the Para 10 cap instead).',
  },
  {
    id: 'n2-17', notice: 2,
    title: 'Boundary: entity FCY borrowing exactly at the RM100M cap from an unrelated Non-Resident',
    who: 'Resident company',
    what: 'Borrowing exactly RM100 million equivalent in aggregate in Foreign Currency from a Non-Resident outside its Group',
    amount: 100000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para10'],
    rationale: 'Part B, Para 10 caps FCY borrowing from outside the Group at RM100 million equivalent in aggregate — exactly RM100 million is within (not exceeding) that cap.',
  },
  {
    id: 'n2-18', notice: 2,
    title: 'Entity FCY borrowing from a NRFI, exceeding RM100M cap',
    who: 'Resident company',
    what: 'Borrowing RM150 million equivalent in Foreign Currency from a Non-Resident Financial Institution (NRFI)',
    amount: 150000000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para10'],
    rationale: 'Part B, Para 10(b) caps FCY borrowing from a NRFI at RM100 million equivalent in aggregate on a group basis — RM150 million exceeds it.',
  },
  {
    id: 'n2-19', notice: 2,
    title: 'Entity refinancing outstanding approved FCY borrowing',
    who: 'Resident company',
    what: 'Refinancing the outstanding principal and accrued profit of a previously-approved FCY borrowing from a LOB, subject to compliance with the original paragraph requirements',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para11'],
    rationale: 'Part B, Para 11: a Resident Entity may refinance outstanding approved Borrowing under paragraphs 6 to 10, subject to compliance with the respective paragraph.',
  },
  {
    id: 'n2-20', notice: 2,
    title: 'Debt swap: Ringgit debt into FCY debt with a LOB, FCY delivered for FCY-asset investment',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Swapping its existing Ringgit debt into Foreign Currency debt with a Licensed Onshore Bank, with FCY delivered at inception that is then used to invest in a Foreign Currency Asset',
    expectVerdict: ['CONDITIONAL'],
    expectRefHints: ['para12'],
    rationale: 'Part C, Para 12: swapping Ringgit debt into FCY debt with a LOB is treated as FCY Borrowing, but any FCY delivered at inception and used for FCY Asset investment must comply with Notice 3 for a Resident with DRB.',
  },
  {
    id: 'n2-21', notice: 2,
    title: 'Non-Resident individual borrowing Ringgit from Resident employer in Malaysia',
    who: 'Non-Resident individual employee',
    what: 'Borrowing RM500,000 in Ringgit from his employer in Malaysia for use in Malaysia',
    amount: 500000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para13'],
    rationale: 'Part D, Para 13(c): a Non-Resident Individual may borrow Ringgit in any amount from an employer in Malaysia for use in Malaysia.',
  },
  {
    id: 'n2-22', notice: 2,
    title: 'Non-Resident borrowing Ringgit from a Resident for Real Sector Activity',
    who: 'Non-Resident company (not a NRFI)',
    what: 'Borrowing RM40 million in Ringgit from a Resident lender to finance Real Sector Activity (a manufacturing facility) in Malaysia',
    amount: 40000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para14'],
    rationale: 'Part D, Para 14(a): a Non-Resident excluding a NRFI may borrow Ringgit in any amount from a Resident to finance Real Sector Activity in Malaysia.',
  },
  {
    id: 'n2-23', notice: 2,
    title: 'Non-Resident borrowing Ringgit from a Resident stockbroker for margin financing',
    who: 'Non-Resident investor',
    what: 'Obtaining Ringgit margin financing from a Resident stockbroking company to purchase Bursa Malaysia-listed shares',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para14'],
    rationale: 'Part D, Para 14(b): a Non-Resident may borrow Ringgit from a Resident stockbroker for margin financing on Bursa Malaysia.',
  },
  {
    id: 'n2-24', notice: 2,
    title: 'Non-Resident overdraft from a LOB exceeding the 2-business-day limit',
    who: 'Non-Resident custodian bank',
    what: 'Maintaining a Ringgit overdraft facility with a LOB for 5 business days to avoid a Bursa Malaysia settlement failure, with no roll-over requested',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para16'],
    rationale: 'Part D, Para 16(b) permits such an overdraft only up to a maximum of 2 business days with no roll-over — 5 business days exceeds the permitted window.',
  },
  {
    id: 'n2-25', notice: 2,
    title: 'Non-Resident repo borrowing from a LOB, within RM10M cap',
    who: 'Non-Resident investor',
    what: 'Borrowing RM7 million in Ringgit from a LOB via a repurchase agreement',
    amount: 7000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para16'],
    rationale: 'Part D, Para 16(c): a Non-Resident may borrow up to RM10 million via a repurchase or sale-buy-back agreement with a LOB — RM7 million is within that cap.',
  },
  {
    id: 'n2-26', notice: 2,
    title: 'Non-Resident FCY borrowing from a Resident, beyond Notice 3 limits',
    who: 'Non-Resident company',
    what: 'Borrowing RM60 million equivalent in Foreign Currency from a Resident entity that itself has Domestic Ringgit Borrowing and is subject to the RM50 million annual Notice 3 investment cap',
    amount: 60000000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para17'],
    rationale: 'Part D, Para 17(b): FCY borrowing by a Non-Resident from a Resident (other than a LOB or Immediate Family Member) is capped at the limits set out in Notice 3 Parts A/B — RM60 million exceeds the lending Resident\'s RM50 million annual cap.',
  },
  {
    id: 'n2-27', notice: 2,
    title: 'LOB obtaining a Financial Guarantee for its own account, any amount',
    who: 'Licensed Onshore Bank',
    what: 'Obtaining a Financial Guarantee of RM500 million in Ringgit for its own account from a Non-Resident bank',
    amount: 500000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para20'],
    rationale: 'Part G, Para 20(a): a LOB may obtain a Financial Guarantee in any amount in Ringgit or FCY for its own account.',
  },
  {
    id: 'n2-28', notice: 2,
    title: 'Non-bank Resident guarantor giving a Financial Guarantee for a Non-Resident SPV borrowing, ultimately utilised by the guarantor',
    who: 'Resident company (non-bank guarantor)',
    what: 'Giving a Financial Guarantee to secure FCY borrowing obtained by a Non-Resident SPV, where the borrowing proceeds are ultimately utilised by the Resident guarantor itself',
    expectVerdict: ['CONDITIONAL', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para22'],
    rationale: 'Part G, Para 22(a): where the underlying Borrowing secured by the Financial Guarantee is ultimately utilised by the Resident guarantor, it is deemed Borrowing by the Resident guarantor, subject to the Notice 2 external borrowing limits.',
  },
  {
    id: 'n2-29', notice: 2,
    title: 'Resident giving a Non-Financial Guarantee (performance bond) to a Non-Resident, any amount',
    who: 'Resident construction company',
    what: 'Giving a performance bond (Non-Financial Guarantee) of USD20 million to a Non-Resident project owner to secure supply of construction services',
    amount: 20000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para25'],
    rationale: 'Part G, Para 25: a Resident may give a Non-Financial Guarantee (e.g. a performance bond) in any amount in FCY or Ringgit to a Non-Resident.',
  },
  {
    id: 'n2-30', notice: 2,
    title: 'Payment to a Non-Resident lender under a called-up Non-Financial Guarantee, paid in Ringgit',
    who: 'Resident company',
    what: 'Paying a Non-Resident lender in Ringgit, instead of Foreign Currency, after its Non-Financial Guarantee is called upon (the guarantee was not issued for use in Malaysia)',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para26'],
    rationale: 'Part G, Para 26: payment to a Non-Resident under a Non-Financial Guarantee must be made in Foreign Currency, UNLESS the guarantee was for use in Malaysia (in which case Ringgit or FCY is allowed) — here it was not for use in Malaysia, so Ringgit payment is not permitted.',
  },

  // ── Notice 3 — Investment in Foreign Currency Asset (DRB) ──
  {
    id: 'n3-01', notice: 3,
    title: 'Regression: one housing loan + one vehicle loan together is still WITHOUT DRB',
    who: 'Resident individual with exactly ONE outstanding housing loan AND exactly ONE outstanding vehicle loan at the same time, and no other Ringgit borrowing from any Resident',
    what: 'Converting RM1.5 million from Ringgit to invest in foreign-listed stocks',
    amount: 1500000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million', 'RM2 million'],
    rationale: 'One housing loan + one vehicle loan is the excluded DRB combination, NOT "more than one" of either type — this Resident is WITHOUT DRB, so Part A Para 1 (UNLIMITED) governs, not the RM1M Para 2 cap.',
  },
  {
    id: 'n3-02', notice: 3,
    title: 'Two housing loans triggers DRB, RM1M cap exceeded',
    who: 'Resident individual with TWO outstanding housing loans and no other Ringgit borrowing',
    what: 'Converting RM1.2 million from Ringgit to invest in a foreign currency fixed deposit',
    amount: 1200000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'TWO housing loans (more than one of the same type) gives this Resident DRB, so the RM1 million/year conversion cap (Part A, Para 2(c)) applies and is exceeded.',
  },
  {
    id: 'n3-03', notice: 3,
    title: 'No Ringgit borrowing at all — unlimited investment',
    who: 'Resident individual with no Ringgit borrowing of any kind',
    what: 'Converting RM5 million from Ringgit to invest in foreign-listed stocks',
    amount: 5000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 1: a Resident Individual without DRB may invest any amount in FCY assets.',
  },
  {
    id: 'n3-04', notice: 3,
    title: 'Joint investment, neither party has DRB — must stay unlimited',
    who: 'Two Resident individuals, joint accountholders, NEITHER of whom has any Domestic Ringgit Borrowing',
    what: 'Jointly converting RM3 million from their joint Ringgit account into a joint foreign currency fixed deposit',
    amount: 3000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million', 'RM2 million'],
    rationale: 'With no DRB on either side, Part A Para 1 (UNLIMITED) governs the whole joint investment — the RM1M/RM2M joint-FCA FAQ only engages when at least one party has DRB.',
  },
  {
    id: 'n3-06', notice: 3,
    title: 'Entity with DRB using LOB FCY borrowing for Direct Investment Abroad',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Using RM80 million equivalent of Foreign Currency borrowing obtained from a Licensed Onshore Bank to fund a Direct Investment Abroad (acquiring 25% equity in a foreign company)',
    amount: 80000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    mustNotMention: ['RM50 million'],
    rationale: 'Part B, Para 4(b): LOB FCY borrowing used for DIA is unlimited — the RM50 million/year cap (Para 4(c)) only applies to conversion-funded, non-DIA investment.',
  },
  {
    id: 'n3-07', notice: 3,
    title: 'Boundary: individual WITH DRB converting exactly RM1,000,000 — at the cap',
    who: 'Resident individual with Domestic Ringgit Borrowing (two outstanding vehicle loans)',
    what: 'Converting exactly RM1,000,000 from Ringgit to invest in foreign-listed stocks this calendar year, with no other FC asset investment so far this year',
    amount: 1000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2(c): a Resident Individual with DRB may convert up to RM1 million equivalent per calendar year — exactly RM1,000,000 is within (not exceeding) that cap.',
  },
  {
    id: 'n3-08', notice: 3,
    title: 'Boundary: individual WITH DRB converting RM1,000,001 — RM1 over the cap',
    who: 'Resident individual with Domestic Ringgit Borrowing (two outstanding housing loans)',
    what: 'Converting RM1,000,001 from Ringgit to invest in a foreign currency fixed deposit this calendar year, with no other FC asset investment so far this year',
    amount: 1000001, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2(c): the RM1 million per calendar year cap for a Resident Individual with DRB is exceeded by RM1, however marginal — the conversion is not permitted without approval.',
  },
  {
    id: 'n3-09', notice: 3,
    title: 'Individual with DRB using offshore FCY funds (not from conversion) for unlimited investment',
    who: 'Resident individual with Domestic Ringgit Borrowing (three outstanding vehicle loans)',
    what: 'Investing RM8 million equivalent in foreign-listed stocks using Foreign Currency funds already held outside Malaysia (not Export of Goods proceeds, not from Ringgit conversion)',
    amount: 8000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 2(a): a Resident Individual with DRB may invest any amount using FCY funds from outside Malaysia (excluding Export of Goods proceeds) — the RM1 million cap (2(c)) only applies to Ringgit-conversion-sourced investment.',
  },
  {
    id: 'n3-10', notice: 3,
    title: 'Individual with DRB buying real estate abroad for own accommodation while studying',
    who: 'Resident individual with Domestic Ringgit Borrowing (two outstanding housing loans), studying abroad',
    what: 'Purchasing real estate outside Malaysia for his own accommodation while pursuing full-time education abroad, with documentary evidence of enrolment',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    mustNotMention: ['RM1 million'],
    rationale: 'Part A, Para 2(b): real estate abroad for own/immediate-family accommodation for education, employment or migration purposes is unlimited — the RM1 million conversion cap does not apply.',
  },
  {
    id: 'n3-11', notice: 3,
    title: 'Individual with DRB buying real estate abroad for a non-family friend',
    who: 'Resident individual with Domestic Ringgit Borrowing (two outstanding vehicle loans)',
    what: 'Purchasing real estate outside Malaysia for the accommodation of a close friend (not an Immediate Family Member) who is migrating abroad',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q5'],
    rationale: 'Notice 3 FAQ Q5: a Resident individual may only purchase property abroad for their own account or Immediate Family Members under the permitted purposes — a non-family friend does not qualify.',
  },
  {
    id: 'n3-12', notice: 3,
    title: 'Entity with DRB converting Ringgit, within RM50M/year cap',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Converting RM35 million from Ringgit this calendar year to invest in foreign-listed equities for non-DIA purposes',
    amount: 35000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part B, Para 4(c): a Resident Entity with DRB may convert up to RM50 million equivalent per calendar year for non-DIA purposes — RM35 million is within that cap.',
  },
  {
    id: 'n3-13', notice: 3,
    title: 'Boundary: entity with DRB converting exactly RM50,000,000 — at the cap',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Converting exactly RM50,000,000 from Ringgit this calendar year for non-DIA foreign currency asset investment, with no other conversion so far this year',
    amount: 50000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part B, Para 4(c): the RM50 million per calendar year cap is exactly met, not exceeded, so the conversion remains permitted.',
  },
  {
    id: 'n3-14', notice: 3,
    title: 'Boundary: entity with DRB converting RM50,000,001 — RM1 over the cap',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Converting RM50,000,001 from Ringgit this calendar year for non-DIA foreign currency asset investment, with no other conversion so far this year',
    amount: 50000001, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para4'],
    rationale: 'Part B, Para 4(c): the RM50 million per calendar year cap is exceeded by RM1, so only the amount exceeding the cap requires prior BNM approval (per FAQ Q17) — without approval the excess is not permitted.',
  },
  {
    id: 'n3-15', notice: 3,
    title: 'Entity with DRB exceeding the RM50M cap — partial approval pathway',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Converting RM65 million from Ringgit this calendar year for non-DIA investment in foreign currency assets',
    amount: 65000000, currency: 'RM',
    expectVerdict: ['REQUIRES_APPROVAL', 'NOT_PERMITTED'],
    expectRefHints: ['q17'],
    rationale: 'Notice 3 FAQ Q17: only the amount exceeding the RM50 million annual aggregate limit requires prior BNM approval — RM65 million exceeds the cap by RM15 million, which needs approval.',
  },
  {
    id: 'n3-16', notice: 3,
    title: 'Entity without DRB, unlimited offshore investment',
    who: 'Resident company with no Domestic Ringgit Borrowing of any kind',
    what: 'Converting RM200 million from Ringgit to invest in a portfolio of foreign-listed bonds',
    amount: 200000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para3'],
    mustNotMention: ['RM50 million'],
    rationale: 'Part B, Para 3: a Resident Entity without DRB may invest in FCY Asset up to any amount.',
  },
  {
    id: 'n3-17', notice: 3,
    title: 'LOB investing in FCY Asset for its own account, unlimited',
    who: 'Licensed Onshore Bank',
    what: 'Investing RM500 million equivalent in Foreign Currency Asset for its own proprietary trading account',
    amount: 500000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5: a LOB may invest in Foreign Currency Asset up to any amount for its own account.',
  },
  {
    id: 'n3-18', notice: 3,
    title: 'SC-licensed fund manager investing FCY Asset onshore on behalf of clients, unlimited',
    who: 'Resident Entity licensed by the Securities Commission Malaysia for fund management',
    what: 'Investing RM300 million in Foreign Currency Asset onshore on behalf of its Resident clients',
    amount: 300000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para6'],
    rationale: 'Part C, Para 6: a SC-licensed Entity may invest in Foreign Currency Asset ONSHORE on behalf of its clients up to ANY amount.',
  },
  {
    id: 'n3-19', notice: 3,
    title: 'Licensed insurer investing offshore for a Resident client WITH DRB, exceeding the 50% NAV limit',
    who: 'Licensed insurer',
    what: 'Investing 70% of the NAV of an investment-linked fund offshore on behalf of a Resident client with DRB, where none of paragraphs 2(a), 2(c)(i)-(ii), 4(a) or 4(c)(i)-(iii) can be ascertained to apply',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para7'],
    rationale: 'Part C, Para 7-8(b): a licensed insurer may invest offshore on behalf of a Resident client WITH DRB up to only 50% of the NAV (aggregated at insurer level) unless the higher exception paragraphs apply — 70% exceeds the 50% limit here.',
  },
  {
    id: 'n3-20', notice: 3,
    title: 'Licensed insurer investing offshore for a Non-Resident client, unlimited',
    who: 'Licensed insurer',
    what: 'Investing 100% of the NAV of an investment-linked fund offshore on behalf of a Non-Resident client',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para7'],
    rationale: 'Part C, Para 7-8(a): a licensed insurer may invest offshore on behalf of a client who is a Non-Resident up to the full NAV of the fund.',
  },
  {
    id: 'n3-21', notice: 3,
    title: 'SC-licensed fund manager investing offshore for a Resident client WITH DRB, within 50% NAV limit',
    who: 'Resident Entity licensed by SC Malaysia for fund management',
    what: 'Investing 45% of the total funds offshore in conventional (non-Shariah) FCY assets on behalf of a Resident client with DRB',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para9'],
    rationale: 'Part C, Para 9-10: a SC-licensed fund manager may invest offshore on behalf of a Resident client WITH DRB up to 50% of the total funds (aggregated at the Resident Entity\'s level) — 45% is within that limit.',
  },
  {
    id: 'n3-24', notice: 3,
    title: 'DRB combination edge case: one vehicle loan plus a sundry-expense credit card facility — still WITHOUT DRB',
    who: 'Resident individual with exactly ONE outstanding vehicle loan and a credit card facility used solely for sundry office expenses, no other Ringgit borrowing',
    what: 'Converting RM3 million from Ringgit to invest in a foreign currency fixed deposit',
    amount: 3000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1'],
    mustNotMention: ['RM1 million'],
    rationale: 'Notice 3 FAQ Q15 (entity DRB logic, applying the same sundry-expense exclusion via the DRB definition) and the DRB glossary: one vehicle loan plus a credit/financing facility used solely for sundry expenses does not constitute DRB — this Resident remains WITHOUT DRB under Part A, Para 1 (UNLIMITED).',
  },
  {
    id: 'n3-25', notice: 3,
    title: 'DRB combination edge case: TWO vehicle loans (no housing loan) triggers DRB',
    who: 'Resident individual with exactly TWO outstanding vehicle loans and no other Ringgit borrowing',
    what: 'Converting RM4 million from Ringgit to invest in foreign-listed stocks',
    amount: 4000000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para2'],
    rationale: 'Notice 3 FAQ Q3: having more than one (1) vehicle loan means the Resident individual is deemed to have DRB — this triggers the RM1 million/year cap (Para 2(c)), which RM4 million exceeds.',
  },
  {
    id: 'n3-26', notice: 3,
    title: 'Resident entity deemed to have DRB via its parent-subsidiary Resident Group',
    who: 'Resident subsidiary company with NO Ringgit borrowing of its own, but whose Resident parent (same parent-subsidiary Group) has Domestic Ringgit Borrowing',
    what: 'Converting RM60 million from Ringgit this calendar year to invest in foreign currency assets',
    amount: 60000000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['q15'],
    rationale: 'Notice 3 FAQ Q15: a Resident entity is deemed to have DRB when another Resident entity with which it has a parent-subsidiary relationship has DRB — the RM50 million/year aggregate cap therefore applies across the Group, and RM60 million exceeds it.',
  },
  {
    id: 'n3-27', notice: 3,
    title: 'Resident entity borrowing from its Resident Direct Shareholder — excluded from DRB',
    who: 'Resident company that has borrowed Ringgit solely from its Resident Direct Shareholder, and has no other Ringgit borrowing',
    what: 'Converting RM30 million from Ringgit to invest in foreign-listed equities',
    amount: 30000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q15'],
    mustNotMention: ['RM50 million'],
    rationale: 'Notice 3 FAQ Q15(a): borrowing obtained from a Resident Direct Shareholder or another Resident entity with a parent-subsidiary relationship is NOT considered DRB — this Resident remains WITHOUT DRB and unlimited under Part B, Para 3.',
  },
  {
    id: 'n3-28', notice: 3,
    title: 'Resident with DRB transferring digital assets from a registered DAX to an offshore wallet, within RM1M cap',
    who: 'Resident individual with Domestic Ringgit Borrowing (two outstanding housing loans)',
    what: 'Transferring RM700,000 worth of digital assets from a registered Malaysian digital asset exchange (DAX) to an offshore digital wallet',
    amount: 700000, currency: 'RM',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['q9'],
    rationale: 'Notice 3 FAQ Q9: transferring digital assets from a registered DAX to an offshore wallet is subject to the investment in FC asset limit for a Resident with DRB — RM700,000 is within the RM1 million annual cap.',
  },
  {
    id: 'n3-29', notice: 3,
    title: 'Resident purchasing digital assets on a registered DAX settled in Ringgit, no investment limit',
    who: 'Resident individual with Domestic Ringgit Borrowing',
    what: 'Purchasing RM2 million worth of digital assets on a registered Malaysian digital asset exchange (DAX), settled entirely in Ringgit with no transfer offshore',
    amount: 2000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q8'],
    mustNotMention: ['RM1 million'],
    rationale: 'Notice 3 FAQ Q8: a Resident is free to purchase digital assets on a registered DAX in Malaysia without any investment limit, as long as it is settled in Ringgit.',
  },
  {
    id: 'n3-30', notice: 3,
    title: 'Resident individual with DRB investing in a non-exchange-rate derivative via margin account, near the cap',
    who: 'Resident individual with Domestic Ringgit Borrowing (two outstanding vehicle loans)',
    what: 'Remitting RM950,000 this calendar year to a margin account with a Non-Resident futures broker to trade equity options (a non-exchange-rate derivative), with no other FC asset investment so far this year',
    amount: 950000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q13'],
    rationale: 'Notice 3 FAQ Q13: the investment amount for non-exchange-rate derivatives is computed on total remittance to the margin account, subject to the RM1 million annual aggregate limit — RM950,000 is within that cap.',
  },

  // ── Notice 4 — Payment and Receipt ──
  {
    id: 'n4-01', notice: 4,
    title: 'FCY payment from Resident to Non-Resident for an import',
    who: 'Resident company',
    what: 'Paying USD300,000 to a Non-Resident supplier in Foreign Currency to settle an import of goods',
    amount: 300000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5: a Resident may pay a Non-Resident in FCY for any purpose except a short list of derivative transactions — an import settlement is not on that list.',
  },
  {
    id: 'n4-02', notice: 4,
    title: 'FCY payment between two Residents for an unlisted domestic purpose',
    who: 'Resident individual',
    what: 'Paying another Resident individual in US Dollars for rental of a holiday home in Malaysia (both parties are Malaysian residents, no family relationship, no LOB or Global Supply Chain involvement)',
    amount: 10000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part C, Para 4 only permits FCY payment between Residents for a specific listed set of purposes (family, education/employment/migration abroad, LOB dealings, Global Supply Chain, etc.) — domestic holiday-home rent is not on that list.',
  },
  {
    id: 'n4-03', notice: 4,
    title: 'Non-Resident repatriating Ringgit-asset divestment proceeds',
    who: 'Non-Resident individual',
    what: 'Repatriating proceeds from the sale of a Ringgit-denominated asset out of Malaysia, converting the proceeds into Foreign Currency before transfer',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para8'],
    rationale: 'Part E, Para 8: a Non-Resident may repatriate funds from Malaysia provided repatriation is in FCY and the Ringgit-to-FCY conversion follows Notice 1 Part B.',
  },
  {
    id: 'n4-04', notice: 4,
    title: 'Ringgit payment to a Non-Resident from a court judgement',
    who: 'Resident company',
    what: 'Making a Ringgit payment to a Non-Resident in Malaysia arising from a court judgement, where the underlying transaction complies with the FEP Notices',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para3'],
    rationale: 'Part B, Para 3 permits Ringgit payment/receipt for a court judgement where the underlying transaction is FEP-compliant.',
  },
  {
    id: 'n4-05', notice: 4,
    title: 'Non-Resident individual Ringgit payment to a Resident Immediate Family Member',
    who: 'Non-Resident individual',
    what: 'Paying RM200,000 in Ringgit to his Resident sister (Immediate Family Member) in Malaysia for any purpose',
    amount: 200000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q1'],
    rationale: 'Notice 4 "Payment in Ringgit by Non-Resident" FAQ Q1: a Non-Resident individual may pay a Resident Immediate Family Member in Ringgit or FCY for any purpose.',
  },
  {
    id: 'n4-06', notice: 4,
    title: 'Non-Resident receiving Ringgit payment without an External Account',
    who: 'Non-Resident company',
    what: 'Attempting to receive a Ringgit payment from a Resident counterparty without maintaining an External Account',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q2'],
    rationale: 'Notice 4 "Payment in Ringgit by Non-Resident" FAQ Q2: a Non-Resident must maintain an External Account to receive a Ringgit payment — without one, the receipt is not permitted.',
  },
  {
    id: 'n4-07', notice: 4,
    title: 'Non-Resident transferring funds between two of its own External Accounts',
    who: 'Non-Resident individual',
    what: 'Transferring RM500,000 in Ringgit from his External Account at one LOB to another External Account he holds at a different LOB',
    amount: 500000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q3'],
    rationale: 'Notice 4 "Payment in Ringgit by Non-Resident" FAQ Q3: a Non-Resident may transfer Ringgit between his own multiple External Accounts.',
  },
  {
    id: 'n4-08', notice: 4,
    title: 'Resident Entity paying another Resident in FCY for education abroad of an employee\'s child',
    who: 'Resident company',
    what: 'Paying a Resident education agent in Foreign Currency on behalf of an employee, for the employee\'s child\'s education abroad',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part C, Para 4: FCY payment between Residents is permitted for purposes including education abroad of an Immediate Family Member.',
  },
  {
    id: 'n4-09', notice: 4,
    title: 'Resident paying another Resident in FCY for a Global Supply Chain pass-through obligation',
    who: 'Resident manufacturing company',
    what: 'Paying a Resident vendor in Foreign Currency for goods supplied as part of a Global Supply Chain arrangement, where the vendor itself has a FCY obligation to an upstream Non-Resident supplier',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part C, Para 4 and footnote 2: a Resident may pay another Resident in FCY for Global Supply Chain pass-through payments where genuine upstream FCY obligations exist.',
  },
  {
    id: 'n4-10', notice: 4,
    title: 'Resident paying a Resident vendor in FCY purely on preference, no FC obligation and locally-sourced goods',
    who: 'Resident retail company',
    what: 'Paying a Resident vendor in US Dollars for locally-sourced goods, where the vendor has no Foreign Currency obligations of its own and the goods are not part of any cross-border supply chain',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q11'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q11: where there are no underlying FC obligations and the goods are locally sourced, this does not qualify as Global Supply Chain — payment must be made in Ringgit.',
  },
  {
    id: 'n4-11', notice: 4,
    title: 'Resident converting Ringgit to FCY specifically to pay under a Global Supply Chain arrangement',
    who: 'Resident company',
    what: 'Converting Ringgit to US Dollars in order to make a payment to a Resident vendor under a Global Supply Chain arrangement',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q10'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q10: a Resident cannot convert Ringgit to FCY to pay under Global Supply Chain — the FCY must come from a Trade FCA or FCY trade financing facility.',
  },
  {
    id: 'n4-12', notice: 4,
    title: 'Resident paying for ancillary services in FCY where genuine FC obligations and FC proceeds exist',
    who: 'Resident logistics company',
    what: 'Paying a Resident freight forwarder in Foreign Currency for ancillary logistics services, where the Resident company has genuine FC obligations abroad and holds FC proceeds from exports',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q12'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q12: FCY settlement for ancillary services is allowed where FC obligations exist abroad and the payer has FC proceeds available.',
  },
  {
    id: 'n4-13', notice: 4,
    title: 'Resident hedging a commodity exposure directly with a Non-Resident counterparty, within underlying exposure',
    who: 'Resident commodity trading company',
    what: 'Entering a commodity derivative directly with a Non-Resident counterparty to hedge crude palm oil exposure, with the notional amount matching its underlying physical exposure',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q14'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q14: a Resident may hedge commodity exposure via a Resident futures broker or directly with a Non-Resident counterparty, up to the underlying exposure.',
  },
  {
    id: 'n4-14', notice: 4,
    title: 'Resident entity entering an FX contract directly with a Non-Resident counterparty',
    who: 'Resident trading company',
    what: 'Entering a foreign exchange forward contract directly with a Non-Resident bank counterparty, bypassing any Licensed Onshore Bank or licensed money changer',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q16'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q16: a Resident entity cannot enter an FX contract directly with a Non-Resident counterparty — it must transact via a LOB or licensed money changer (per Notice 1).',
  },
  {
    id: 'n4-15', notice: 4,
    title: 'NRFI making a Ringgit payment on behalf of a customer under remittance business licence',
    who: 'Non-Resident Financial Institution licensed for remittance business',
    what: 'Making a Ringgit payment in Malaysia on behalf of its remittance customer, under its remittance business licence',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para7'],
    rationale: 'Part D, Para 7: a person licensed for remittance business may make or receive a payment on behalf of its customers in the ordinary course of that licensed business.',
  },
  {
    id: 'n4-16', notice: 4,
    title: 'NR Intermediary providing Ringgit financing to its NR client for Ringgit Asset purchase',
    who: 'Non-Resident Intermediary (custodian)',
    what: 'Extending Ringgit financing to its Non-Resident client to fund the client\'s purchase of Ringgit-denominated securities',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para12'],
    rationale: 'Part F, Para 12: a NR Intermediary or NRFI is prohibited from providing Ringgit financing to its clients.',
  },
  {
    id: 'n4-17', notice: 4,
    title: 'NRFI making Ringgit payment for NR client trade settlement via External Account',
    who: 'Non-Resident Financial Institution',
    what: 'Making a Ringgit payment via its External Account to settle a Ringgit Asset trade on behalf of its Non-Resident client',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para10'],
    rationale: 'Part F, Para 10: a NRFI may make Ringgit payments for the purpose of settling its NR client\'s trade, via the External Account.',
  },
  {
    id: 'n4-18', notice: 4,
    title: 'Resident individual maintaining a Foreign Currency Account jointly with a LOB',
    who: 'Resident individual',
    what: 'Opening and maintaining a Foreign Currency Account jointly with his spouse, with a Licensed Onshore Bank',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para14'],
    rationale: 'Part F, Para 14: a Resident Individual may maintain a FCA with a LOB or NRFI, solely or jointly — but per footnote 5, if a joint accountholder has DRB, Notice 3 Part A applies to the joint funding.',
  },
  {
    id: 'n4-19', notice: 4,
    title: 'Resident individual with DRB transferring FC funds between his own two FCAs',
    who: 'Resident individual with Domestic Ringgit Borrowing',
    what: 'Transferring Foreign Currency funds from one of his own Foreign Currency Accounts to another of his own Foreign Currency Accounts',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para15'],
    rationale: 'Part F, Para 15: a Resident Individual may transfer FC funds between his own FCAs, subject to Notice 3 Part A where relevant (e.g. if the funds originated from Ringgit conversion and DRB applies).',
  },
  {
    id: 'n4-20', notice: 4,
    title: 'Resident Entity maintaining a Foreign Currency Account, subject to Notice 3',
    who: 'Resident company with Domestic Ringgit Borrowing',
    what: 'Maintaining a Foreign Currency Account funded via Ringgit conversion exceeding the RM50 million annual cap, without BNM approval',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para16'],
    rationale: 'Part F, Para 16: a Resident Entity\'s FCA is subject to Notice 3 Part B — funding it via Ringgit conversion beyond the RM50 million/year cap for an Entity with DRB is not permitted without approval.',
  },
  {
    id: 'n4-21', notice: 4,
    title: 'Resident Intermediary failing to segregate Resident and Non-Resident client funds in its FCA',
    who: 'Resident Intermediary (custodian/broker)',
    what: 'Commingling Resident and Non-Resident client funds within a single Foreign Currency Account, with no segregation',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para17'],
    rationale: 'Part F, Para 17: a Resident Intermediary must segregate Resident and Non-Resident client funds within its FCA — commingling is not permitted.',
  },
  {
    id: 'n4-22', notice: 4,
    title: 'Non-Resident maintaining a Foreign Currency Account in Malaysia',
    who: 'Non-Resident individual',
    what: 'Opening and maintaining a Foreign Currency Account with a Licensed Onshore Bank in Malaysia',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para18'],
    rationale: 'Part F, Para 18: a Non-Resident may maintain a Foreign Currency Account in Malaysia.',
  },
  {
    id: 'n4-23', notice: 4,
    title: 'NR Intermediary custodian Ringgit payment for settlement of a Ringgit Asset, on behalf of NR client',
    who: 'Non-Resident Intermediary acting as custodian',
    what: 'Making a Ringgit payment to settle the purchase of a Ringgit-denominated bond on behalf of its Non-Resident client',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para11'],
    rationale: 'Part F, Para 11: a NR Intermediary or NRFI acting as custodian may make Ringgit payments for the settlement of Ringgit Asset transactions on behalf of NR clients.',
  },
  {
    id: 'n4-24', notice: 4,
    title: 'NR Intermediary custodian failing Appendix compliance requirements',
    who: 'Non-Resident Intermediary acting as custodian',
    what: 'Making Ringgit payments for client trade settlement without complying with the recordkeeping and reporting requirements set out in the relevant Appendix',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para13'],
    rationale: 'Part F, Para 13: a NR Intermediary or NRFI custodian must comply with the Appendix requirements — failing to do so means the payment activity is not properly permitted.',
  },
  {
    id: 'n4-25', notice: 4,
    title: 'External Account payment made without documentary evidence of FEP compliance',
    who: 'Non-Resident individual',
    what: 'Making a payment from his External Account without providing the LOB any documentary evidence that the underlying transaction complies with the FEP Notices',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para9'],
    rationale: 'Part F, Para 9 and footnote 4: payments from an External Account require documentary evidence of compliance with the FEP Notices — without it, the payment should not proceed.',
  },
  {
    id: 'n4-26', notice: 4,
    title: 'Resident entering a Ringgit-referenced derivative with a Non-Resident without Notice 1 approval',
    who: 'Resident company',
    what: 'Entering a derivative contract with a Non-Resident counterparty that is referenced to the Ringgit exchange rate, without any approval or registration under Notice 1',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5(b): FCY payment to/from a Non-Resident is excluded where it relates to a Ringgit-referenced derivative, unless approved — no approval exists here.',
  },
  {
    id: 'n4-27', notice: 4,
    title: 'Non-Resident entering an Exchange Rate Derivative without Notice 1 approval',
    who: 'Non-Resident hedge fund',
    what: 'Entering an Exchange Rate Derivative transaction and making an FCY payment in connection with it, without being registered or approved under Notice 1',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5(c): FCY payment to/from a Non-Resident is excluded where it relates to an Exchange Rate Derivative by that Non-Resident, unless approved under Notice 1 — no such approval exists here.',
  },
  {
    id: 'n4-28', notice: 4,
    title: 'Two Non-Residents making an FCY payment between each other, any purpose',
    who: 'Two Non-Resident companies',
    what: 'Making a Foreign Currency payment of USD2 million between each other, for the purchase of equipment located overseas',
    amount: 2000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para6'],
    rationale: 'Part C, Para 6: a Non-Resident may pay another Non-Resident in FCY for any purpose.',
  },
  {
    id: 'n4-29', notice: 4,
    title: 'Resident individual receiving a misc-expense reimbursement abroad from a friend',
    who: 'Resident individual travelling abroad',
    what: 'Receiving a Foreign Currency reimbursement of miscellaneous travel expenses from a friend who is also a Resident, while both are temporarily overseas',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q2'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q2: a Resident may receive an FCY advance or reimbursement of miscellaneous expenses from another Resident while abroad.',
  },
  {
    id: 'n4-30', notice: 4,
    title: 'Resident paying for a foreign currency unit trust subscription in the fund\'s base currency',
    who: 'Resident individual investor',
    what: 'Paying subscription monies for a Foreign Currency-denominated unit trust fund, in the fund\'s base currency, to a Resident fund management company',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q4'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q4: FC unit trust subscription, redemption and fee payments may be made in the fund\'s base currency.',
  },
  {
    id: 'n4-31', notice: 4,
    title: 'Joint investment, one party has DRB — RM2M combined cap exceeded',
    who: 'Two Resident individuals, joint accountholders; one has DRB (two outstanding vehicle loans), the other has none',
    what: 'Jointly converting RM2.5 million from their joint Ringgit account into a joint foreign currency fixed deposit',
    amount: 2500000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['q7'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q7: DRB in any one joint party caps the WHOLE joint investment at RM1M per person / RM2M combined for two parties — RM2.5 million exceeds it.',
  },
  {
    id: 'n4-32', notice: 4,
    title: 'Joint individuals, both with DRB — RM2M combined cap, within limit',
    who: 'Two Resident individuals, joint accountholders, BOTH of whom have Domestic Ringgit Borrowing (each has two outstanding housing loans)',
    what: 'Jointly converting RM1.8 million from their joint Ringgit account into a joint foreign currency fixed deposit this calendar year',
    amount: 1800000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q7'],
    rationale: 'Notice 4 "Payment in Foreign Currency by Resident" FAQ Q7: DRB in a joint party caps the WHOLE joint investment at RM2 million combined for two parties — RM1.8 million is within that combined cap.',
  },
  {
    id: 'n4-33', notice: 4,
    title: 'Boundary: joint investment with DRB, exactly at the RM2M combined cap',
    who: 'Two Resident individuals, joint accountholders; one has DRB (two outstanding vehicle loans)',
    what: 'Jointly converting exactly RM2,000,000 from their joint Ringgit account into a joint foreign currency fixed deposit this calendar year',
    amount: 2000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q7'],
    rationale: 'Notice 4 FAQ Q7: the combined cap for a 2-party joint investment where one party has DRB is RM2 million — exactly RM2,000,000 is within (not exceeding) that combined threshold.',
  },

  // ── Notice 5 — Securities and Financial Instruments ──
  {
    id: 'n5-01', notice: 5,
    title: 'Resident issuing a Ringgit bond to a Non-Resident',
    who: 'Resident company',
    what: 'Issuing a Ringgit-denominated corporate bond in Malaysia to a Non-Resident institutional investor',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para1'],
    rationale: 'Part A, Para 1(a): permitted, but as a debt security issuance it must also comply with Notice 2 borrowing limits.',
  },
  {
    id: 'n5-02', notice: 5,
    title: 'Non-Resident issuing an FCY bond in Malaysia',
    who: 'Non-Resident company',
    what: 'Issuing a Foreign Currency-denominated bond in Malaysia to any investor',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2-3: a Non-Resident may issue an FCY-denominated security in Malaysia to any person.',
  },
  {
    id: 'n5-03', notice: 5,
    title: 'Bursa Malaysia offering an exchange-rate-linked Ringgit instrument',
    who: 'Bursa Malaysia',
    what: 'Offering a Non-Resident a Ringgit-denominated structured note whose payout is linked to the USD/MYR exchange rate',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para8'],
    rationale: 'Part B, Para 8 explicitly excludes exchange-rate-referenced financial instruments from what Bursa Malaysia may offer Non-Residents.',
  },
  {
    id: 'n5-04', notice: 5,
    title: 'Resident subscribing to a Notice-5 security',
    who: 'Resident individual',
    what: 'Subscribing to a Ringgit-denominated corporate bond issued under Notice 5, subject to compliance with Notices 2, 3 and 4',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para9'],
    rationale: 'Part C, Para 9-10: subscription is permitted subject to compliance with Notices 2, 3 and 4.',
  },
  {
    id: 'n5-05', notice: 5,
    title: 'LOB issuing a Ringgit financial instrument to a Resident',
    who: 'Licensed Onshore Bank',
    what: 'Issuing a Ringgit-denominated structured deposit (Financial Instrument) to a Resident individual client',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para4'],
    rationale: 'Part B, Para 4(a): a LOB may only issue a Ringgit-denominated Financial Instrument in Malaysia to a Non-Resident, not to a Resident.',
  },
  {
    id: 'n5-06', notice: 5,
    title: 'LOB dealing in a Ringgit interest rate derivative with a Non-Resident',
    who: 'Licensed Onshore Bank',
    what: 'Dealing in a Ringgit-denominated interest rate derivative with a Non-Resident counterparty directly (no exchange rate feature)',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part B, Para 5: a LOB may deal in a Ringgit-denominated interest rate derivative or profit rate Islamic derivative with a Non-Resident counterparty.',
  },
  {
    id: 'n5-07', notice: 5,
    title: 'Multilateral Development Bank issuing a Ringgit debt security in Malaysia',
    who: 'Multilateral Development Bank',
    what: 'Issuing a Ringgit-denominated debt security in Malaysia to any investor, subject to compliance with Notice 2',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2-3: a Multilateral Development Bank or Qualified DFI may issue a Ringgit debt security in Malaysia to any person, subject to Notice 2.',
  },
  {
    id: 'n5-08', notice: 5,
    title: 'Resident licensed insurer offering a Ringgit insurance product linked to a Financial Instrument, to a Non-Resident',
    who: 'Resident licensed insurer',
    what: 'Issuing an insurance product linked to a Ringgit-denominated Financial Instrument, offered to a Non-Resident',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para7'],
    rationale: 'Part B, Para 7: a Resident licensed insurer or takaful operator may issue or offer an insurance/takaful product linked to a Ringgit-denominated Financial Instrument to a Non-Resident.',
  },
  {
    id: 'n5-09', notice: 5,
    title: 'Licensed international Islamic bank issuing an FCY Islamic Financial Instrument',
    who: 'Licensed international Islamic bank',
    what: 'Issuing an Islamic Financial Instrument denominated in Foreign Currency to any person, not referenced to exchange rate',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para6'],
    rationale: 'Part B, Para 6: a licensed international Islamic bank may issue an FCY-denominated Islamic Financial Instrument to any person.',
  },
  {
    id: 'n5-10', notice: 5,
    title: 'Non-Resident transferring a Notice-5 security in Malaysia without checking Notice 2/3/4 compliance',
    who: 'Non-Resident institutional investor',
    what: 'Transferring a Ringgit-denominated security issued under Notice 5 to another Non-Resident, without regard to Notice 2, 3 or 4 compliance',
    expectVerdict: ['CONDITIONAL', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para9'],
    rationale: 'Part C, Para 9-10: subscription or transfer of a Notice-5 security is permitted only subject to compliance with Notices 2, 3 and 4 — it is not unconditional.',
  },

  // ── Notice 6 — Import and Export of Currency ──
  {
    id: 'n6-01', notice: 6,
    title: 'Strict cap: traveller exporting RM5,000 cash',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Carrying RM5,000 in Ringgit currency notes out of Malaysia on departure',
    amount: 5000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['ringgit (export)'],
    rationale: 'A traveller may take out at most RM1,000 in Ringgit notes per trip — amounts above that are NOT permitted under any circumstances (no approval pathway exists for this one).',
  },
  {
    id: 'n6-02', notice: 6,
    title: 'Within cap: traveller exporting RM800 cash',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Carrying RM800 in Ringgit currency notes out of Malaysia on departure',
    amount: 800, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['ringgit (export)'],
    rationale: 'RM800 is within the RM1,000 per-trip cap on exporting Ringgit notes.',
  },
  {
    id: 'n6-03', notice: 6,
    title: 'Undeclared Ringgit import above threshold',
    who: 'Traveller entering Malaysia',
    what: 'Bringing RM15,000 in Ringgit currency notes into Malaysia without declaring it to Customs on arrival',
    amount: 15000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['ringgit (import)'],
    rationale: 'Import of Ringgit above RM10,000 must be declared to Customs — bringing it in undeclared is not permitted.',
  },
  {
    id: 'n6-04', notice: 6,
    title: 'Undeclared FCY export above threshold',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Taking USD10,000 in foreign currency notes out of Malaysia without declaring it to the Royal Malaysian Customs Department',
    amount: 10000, currency: 'USD',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['foreign currency'],
    rationale: 'Amounts exceeding RM30,000 equivalent in FCY must be declared to Customs; USD10,000 (well above that, at typical exchange rates) taken out undeclared is a violation.',
  },
  {
    id: 'n6-05', notice: 6,
    title: 'Boundary: traveller exporting exactly RM1,000 cash',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Carrying exactly RM1,000 in Ringgit currency notes out of Malaysia on departure',
    amount: 1000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['ringgit (export)'],
    rationale: 'RM1,000 is exactly at the per-trip cap on exporting Ringgit notes, which is permitted (the cap is "up to RM1,000").',
  },
  {
    id: 'n6-06', notice: 6,
    title: 'Boundary: traveller exporting RM1,001 cash',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Carrying RM1,001 in Ringgit currency notes out of Malaysia on departure',
    amount: 1001, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['ringgit (export)'],
    rationale: 'RM1,001 is RM1 above the RM1,000 per-trip cap on exporting Ringgit notes — not permitted under any circumstances.',
  },
  {
    id: 'n6-07', notice: 6,
    title: 'Boundary: traveller importing exactly RM10,000 cash, undeclared',
    who: 'Traveller entering Malaysia',
    what: 'Bringing exactly RM10,000 in Ringgit currency notes into Malaysia without declaring it to Customs on arrival',
    amount: 10000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['ringgit (import)'],
    rationale: 'Declaration is only required for import of Ringgit ABOVE RM10,000 — exactly RM10,000 does not trigger the declaration requirement.',
  },
  {
    id: 'n6-08', notice: 6,
    title: 'Boundary: traveller importing RM10,001 cash, undeclared',
    who: 'Traveller entering Malaysia',
    what: 'Bringing RM10,001 in Ringgit currency notes into Malaysia without declaring it to Customs on arrival',
    amount: 10001, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['ringgit (import)'],
    rationale: 'RM10,001 exceeds the RM10,000 declarable threshold for Ringgit import — bringing it in undeclared is not permitted.',
  },
  {
    id: 'n6-09', notice: 6,
    title: 'Boundary: traveller exporting FCY just below the RM30,000-equivalent declaration threshold, undeclared',
    who: 'Traveller (Resident) leaving Malaysia',
    what: 'Taking the equivalent of RM29,000 in foreign currency notes out of Malaysia without declaring it to the Royal Malaysian Customs Department',
    amount: 29000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['foreign currency'],
    rationale: 'Declaration is only mandatory above RM30,000 equivalent in Foreign Currency — RM29,000 equivalent taken out undeclared does not breach the threshold.',
  },
  {
    id: 'n6-10', notice: 6,
    title: 'Boundary: traveller importing FCY just above the RM30,000-equivalent declaration threshold, declared',
    who: 'Traveller entering Malaysia',
    what: 'Bringing in the equivalent of RM31,000 in foreign currency notes into Malaysia, properly declared to the Royal Malaysian Customs Department on arrival',
    amount: 31000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['foreign currency'],
    rationale: 'There is no upper limit on FCY import; declaration above RM30,000 equivalent is mandatory and has been properly made here, so the import is permitted.',
  },

  // ── Notice 7 — Export of Goods ──
  {
    id: 'n7-01', notice: 7,
    title: 'Compliant export proceeds receipt',
    who: 'Resident exporter',
    what: 'Receiving the full value of export proceeds within 4 months of shipment, credited into a Trade FCA maintained with a Licensed Onshore Bank',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(a)', 'para1(c)'],
    rationale: 'Part A, Para 1(a)/(c): full-value receipt within 6 months into a Ringgit account or Trade FCA with a LOB is the standard compliant pattern.',
  },
  {
    id: 'n7-02', notice: 7,
    title: 'Export proceeds overdue beyond 6 months, no approved exception',
    who: 'Resident exporter',
    what: 'Export proceeds still not received 8 months after shipment date, and none of the approved Appendix C circumstances (buyer difficulties, disputes, consignment, testing) apply',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c): proceeds must be received within 6 months, extendable to 24 months ONLY in approved Appendix C circumstances — none apply here.',
  },
  {
    id: 'n7-03', notice: 7,
    title: 'Large exporter has not filed the required report',
    who: 'Resident exporter with annual gross exports of RM300 million in the preceding year',
    what: 'Has not submitted any report to the FEP Authority despite exceeding the RM250 million reporting threshold',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['para4'],
    rationale: 'Part C, Para 4: exporters with annual gross exports above RM250 million must report to the FEP Authority as and when required — not having reported is non-compliant.',
  },
  {
    id: 'n7-04', notice: 7,
    title: 'Outstanding proceeds beyond 24 months, not notified',
    who: 'Resident exporter',
    what: 'Export proceeds still outstanding 25 months after shipment, and the exporter has not notified the FEP Authority of the outstanding amount',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5: proceeds outstanding beyond 24 months must be notified to the FEP Authority within 21 days after year-end — failing to notify is non-compliant.',
  },
  {
    id: 'n7-05', notice: 7,
    title: 'Boundary: export proceeds received exactly at the 6-month mark',
    who: 'Resident exporter',
    what: 'Receiving the full value of export proceeds exactly 6 months after the shipment date, credited into a Ringgit account with a Licensed Onshore Bank',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c): the standard repatriation window is 6 months from shipment date — receipt exactly at 6 months is within (not exceeding) that window.',
  },
  {
    id: 'n7-06', notice: 7,
    title: 'Boundary: export proceeds received one day past the 6-month mark, no approved exception',
    who: 'Resident exporter',
    what: 'Receiving export proceeds 1 day after the standard 6-month repatriation window has lapsed, with none of the Appendix C circumstances applicable',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c): the 6-month standard window is exceeded by 1 day with no approved Appendix C exception in play — this is technically non-compliant absent an extension.',
  },
  {
    id: 'n7-07', notice: 7,
    title: 'Extension to 24 months due to buyer financial difficulties',
    who: 'Resident exporter',
    what: 'Export proceeds outstanding 14 months after shipment because the Non-Resident buyer is experiencing genuine financial difficulties, with documentary evidence',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c) and Appendix C(1): buyer financial difficulties is an approved circumstance extending the repatriation window up to 24 months — 14 months is within that extended window.',
  },
  {
    id: 'n7-08', notice: 7,
    title: 'Boundary: export proceeds outstanding exactly at 24 months, buyer dispute ongoing',
    who: 'Resident exporter',
    what: 'Export proceeds still outstanding exactly 24 months after shipment due to a genuine quality dispute raised by the Non-Resident buyer, with supporting documentation',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c) and Appendix C(1): a quality/quantity claim dispute is an approved circumstance, and the extension period maxes out at 24 months — exactly 24 months is within (not exceeding) that ceiling.',
  },
  {
    id: 'n7-09', notice: 7,
    title: 'Boundary: export proceeds outstanding at 24 months and 1 day, dispute resolved, no notification made',
    who: 'Resident exporter',
    what: 'Export proceeds still outstanding 24 months and 1 day after shipment; the underlying dispute has since been resolved, but the exporter has not notified the FEP Authority',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['para5'],
    rationale: 'Part C, Para 5: once outstanding beyond 24 months, the exporter must notify the FEP Authority within 21 days after calendar year-end — not having notified breaches this obligation regardless of the underlying dispute being resolved.',
  },
  {
    id: 'n7-10', notice: 7,
    title: 'Consignment sale with 24-month credit term, fully compliant',
    who: 'Resident exporter',
    what: 'Exporting goods on a consignment sale basis with an agreed 24-month credit term to the Non-Resident consignee, receiving full proceeds within that 24-month window',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c) and Appendix C(2): consignment sale arrangements may have credit terms up to 24 months — receipt within that window is compliant.',
  },
  {
    id: 'n7-11', notice: 7,
    title: 'Goods exported for testing and commissioning, proceeds received within 24 months',
    who: 'Resident exporter (industrial equipment manufacturer)',
    what: 'Exporting machinery for overseas testing and commissioning under a 20-month credit term, receiving full proceeds within that period',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(c)'],
    rationale: 'Part A, Para 1(c) and Appendix C(2): goods exported for testing or commissioning may carry credit terms up to 24 months — 20 months is within that window.',
  },
  {
    id: 'n7-12', notice: 7,
    title: 'Deduction of agency commission and freight from export proceeds',
    who: 'Resident exporter',
    what: 'Receiving export proceeds net of agency commission, advertising expenses, and freight and insurance charges, in line with the sale contract',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(b)'],
    rationale: 'Part A, Para 1(b) and Appendix A(a)/(b): agency commission, advertising, handling, freight and insurance are approved deductions from full export proceeds value.',
  },
  {
    id: 'n7-13', notice: 7,
    title: 'Deduction for a quantity/quality claim by the foreign buyer',
    who: 'Resident exporter',
    what: 'Receiving export proceeds reduced by an agreed discount to settle the Non-Resident buyer\'s legitimate quality claim on a shipment',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(b)'],
    rationale: 'Part A, Para 1(b) and Appendix A(e): a deduction for a quality or quantity claim by the buyer is an approved deduction from the full export proceeds value.',
  },
  {
    id: 'n7-14', notice: 7,
    title: 'Write-off of export proceeds where the Non-Resident buyer is under liquidation',
    who: 'Resident exporter',
    what: 'Writing off export proceeds owed by a Non-Resident buyer that has since entered liquidation, with documentary evidence of the liquidation proceedings',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(b)'],
    rationale: 'Part A, Para 1(b) and Appendix A(j)/Appendix B(b): write-off is an approved offsetting arrangement where the buyer is under liquidation.',
  },
  {
    id: 'n7-15', notice: 7,
    title: 'Goods not for sale: personal effects exported, exempt from receipt obligation',
    who: 'Resident individual relocating overseas',
    what: 'Exporting personal effects and household items as part of relocation abroad, with no sale or export proceeds expected',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 and Appendix D(b): personal effects not for sale are exempt from the export-proceeds receipt obligation entirely.',
  },
  {
    id: 'n7-16', notice: 7,
    title: 'Goods exported under a border trade agreement, exempt from receipt obligation',
    who: 'Resident trader',
    what: 'Exporting goods to a neighbouring country under a recognised border trade agreement arrangement',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 and Appendix D(a): goods exported under a border trade agreement are exempt from the standard export-proceeds receipt obligation.',
  },
  {
    id: 'n7-17', notice: 7,
    title: 'Goods exported for exhibition and reimported afterwards, exempt from receipt obligation',
    who: 'Resident manufacturer',
    what: 'Exporting goods to an overseas trade exhibition with the clear intention of reimporting them into Malaysia after the exhibition concludes, no sale involved',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para2'],
    rationale: 'Part A, Para 2 and Appendix D(b): goods exported for exhibition and reimported are exempt from the export-proceeds receipt obligation.',
  },
  {
    id: 'n7-18', notice: 7,
    title: 'Toll manufacturing arrangement treated as export of goods',
    who: 'Resident toll manufacturer',
    what: 'Processing raw materials owned by a Non-Resident principal into finished goods, then shipping the goods overseas under a toll manufacturing arrangement',
    expectVerdict: ['PERMITTED', 'CONDITIONAL'],
    expectRefHints: ['q4'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q4: a toll manufacturing arrangement is treated as export of goods and is subject to the Notice 7 receipt and repatriation requirements.',
  },
  {
    id: 'n7-19', notice: 7,
    title: 'Resident retaining export proceeds in a Trade FCA with no time limit',
    who: 'Resident exporter',
    what: 'Retaining USD2 million of export proceeds in a Trade Foreign Currency Account with a Licensed Onshore Bank for over 3 years, without converting to Ringgit',
    amount: 2000000, currency: 'USD',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q10'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q10: there is no time limit on retaining export proceeds in a Trade FCA once properly received within the repatriation window.',
  },
  {
    id: 'n7-20', notice: 7,
    title: 'Resident exporter opening multiple Trade FCAs',
    who: 'Resident exporter',
    what: 'Opening and maintaining three separate Trade Foreign Currency Accounts with different Licensed Onshore Banks for different export contracts',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q15'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q15: a Resident exporter may open multiple Trade FCAs.',
  },
  {
    id: 'n7-21', notice: 7,
    title: 'Trade FCA funds used for Foreign Currency Asset investment, subject to Notice 3',
    who: 'Resident exporter with Domestic Ringgit Borrowing',
    what: 'Using retained Trade FCA export proceeds of RM3 million equivalent to invest in foreign-listed equities, with no other FC asset investment so far this year',
    amount: 3000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q16'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q16: export proceeds retained in FC may be used to invest in FC assets, but remain subject to the Notice 3 investment limit for a Resident with DRB — here the funds are FCY-sourced (not Ringgit-converted), so the cap does not bite this transaction.',
  },
  {
    id: 'n7-22', notice: 7,
    title: 'Resident without export proceeds converting Ringgit to FCY for an import obligation',
    who: 'Resident company with no export proceeds of its own',
    what: 'Converting Ringgit to US Dollars with a Licensed Onshore Bank to settle an outstanding import payment obligation',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q17'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q17: a Resident without export proceeds may still convert Ringgit to FCY for import payment or FCY Borrowing repayment obligations.',
  },
  {
    id: 'n7-23', notice: 7,
    title: 'Fund transfer from Trade FCA to Investment FCA, subject to Notice 3',
    who: 'Resident exporter with Domestic Ringgit Borrowing',
    what: 'Transferring RM55 million equivalent from a Trade FCA into an Investment FCA this calendar year, exceeding the RM50 million annual conversion cap with no approval',
    amount: 55000000, currency: 'RM',
    expectVerdict: ['NOT_PERMITTED', 'REQUIRES_APPROVAL'],
    expectRefHints: ['q18'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q18: transfer from a Trade FCA to an Investment FCA is subject to the Notice 3 investment limit — RM55 million exceeds the RM50 million annual cap for an Entity with DRB.',
  },
  {
    id: 'n7-24', notice: 7,
    title: 'Fund transfer from Investment FCA back to Trade FCA, unrestricted',
    who: 'Resident exporter with Domestic Ringgit Borrowing',
    what: 'Transferring RM80 million equivalent from an Investment FCA back into a Trade FCA',
    amount: 80000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q18'],
    mustNotMention: ['RM50 million'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q18: transfer from an Investment FCA back to a Trade FCA is unrestricted, unlike the reverse direction.',
  },
  {
    id: 'n7-25', notice: 7,
    title: 'Offsetting export proceeds against import payment obligations',
    who: 'Resident trading company that both exports and imports goods',
    what: 'Offsetting RM4 million of export proceeds receivable against RM4 million of import payments owed to the same overseas counterparty group, with supporting documentation',
    amount: 4000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['para1(b)'],
    rationale: 'Part A, Para 1(b) and Appendix B(a): offsetting export proceeds against import payment obligations is an approved arrangement.',
  },
  {
    id: 'n7-26', notice: 7,
    title: 'Offsetting export proceeds against an anticipated future FC obligation not yet incurred',
    who: 'Resident exporter',
    what: 'Offsetting export proceeds against an FC obligation that has not yet been incurred, but is merely anticipated for a future transaction',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q12'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q12: offsetting is only permitted against FC obligations already incurred under a Firm Commitment — not merely anticipated future obligations.',
  },
  {
    id: 'n7-27', notice: 7,
    title: 'Offsetting export proceeds directly against an overseas investment',
    who: 'Resident exporter',
    what: 'Attempting to offset export proceeds receivable directly against the cost of an overseas property investment, without any LOB-facilitated trade financing arrangement',
    expectVerdict: ['NOT_PERMITTED'],
    expectRefHints: ['q14'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q14: export proceeds cannot be offset against overseas investments or direct commodity hedging with a Non-Resident counterparty.',
  },
  {
    id: 'n7-28', notice: 7,
    title: 'Offsetting export proceeds against FCY Borrowing repayment via Trade Master Card-style global offsetting',
    who: 'Resident exporter within a multinational Group',
    what: 'Offsetting export proceeds against the repayment of FCY Borrowing obtained under Notice 2, using a global offsetting arrangement administered by the Group treasury centre',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q11'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q11: detailed approved offsetting arrangements include offsetting against FCY Borrowing repayment under Notice 2, including via global offsetting / TMC structures.',
  },
  {
    id: 'n7-29', notice: 7,
    title: 'Export of services mistakenly treated as subject to the 6-month repatriation rule',
    who: 'Resident IT consulting company',
    what: 'Providing consulting services to an overseas client and receiving payment 9 months after invoicing, with no goods shipment involved',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q3'],
    mustNotMention: ['6 months', '24 months'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q3: the repatriation timeline obligations under Notice 7 apply only to export of goods, not export of services or merchanting trade — there is no 6-month deadline for this service payment.',
  },
  {
    id: 'n7-30', notice: 7,
    title: 'Boundary: exporter with annual gross exports just under the RM250M reporting threshold',
    who: 'Resident exporter with annual gross exports of exactly RM249 million in the preceding year',
    what: 'Not having submitted any report to the FEP Authority regarding its export activities',
    amount: 249000000, currency: 'RM',
    expectVerdict: ['PERMITTED'],
    expectRefHints: ['q19'],
    mustNotMention: ['RM250 million'],
    rationale: 'Notice 7 "Export of Goods" FAQ Q19: the reporting obligation is triggered only for exporters with annual gross exports ABOVE RM250 million — RM249 million does not trigger the requirement.',
  },
];
